#!/bin/sh
# SPDX-License-Identifier: GPL-2.0+
#
# Ensure that uncompressed filesystems should not have LZ4_0PADDING set
#

seq=`basename $0`
seqres=$RESULT_DIR/$(echo $0 | awk '{print $((NF-1))"/"$NF}' FS="/")

# get standard environment, filters and checks
. "${srcdir}/common/rc"

cleanup()
{
	cd /
	rm -rf $tmp.*
}

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here
echo "QA output created by $seq"

if [ -z $SCRATCH_DEV ]; then
	SCRATCH_DEV=$tmp/erofs_$seq.img
	rm -f SCRATCH_DEV
fi

localdir="$tmp/$seq"
rm -rf $localdir
mkdir -p $localdir

_scratch_mkfs $localdir >> $seqres.full 2>&1 || _fail "failed to mkfs"

dump.erofs $SCRATCH_DEV | grep 'features:.*0padding' > /dev/null 2>&1 &&
	_fail "0padding is set unexpectedly"

echo Silence is golden
status=0
exit 0
